### PR TITLE
feat: support resolving to image nodes automatically for embedded wikilinks

### PR DESCRIPTION
**Pull request by benclmnt**
- Hi @abhinav, this is the subsequent PR from our discussion in #18 

The overview of the changes: 
- Change the behaviour of the default resolver to add .html only on path with no extensions.
- Change the behaviour of the default renderer to render embedded wikilinks with common image file types as image. Other types are left as simple links (unchanged)

### CODE REVIEW

**Comment by abhinav** [comment]
Thanks, @benclmnt!
I made a couple minor adjustments to address my own nitpicks.
The change looks mostly fine,
except I think there's an issue in how this interacts with parsing.

`![[foo.png]]` will parse as `Node{Target: "foo.png"}` and a text child holding the contents "foo.png".
`![[foo.png|alt text]]` will parse as `Node{Target: "foo.png"}` and a text child holding "alt text".
These will render as `foo.png` and `alt text` respectively.

If we make the following change to testdata/tests.txt, it'll fail because the expectations will not match.

```diff
diff --git a/testdata/tests.txt b/testdata/tests.txt
index 6486691..d1b45f3 100644
--- a/testdata/tests.txt
+++ b/testdata/tests.txt
@@ -104,3 +104,15 @@ Page that [[Does Not Exist|has a label]].
 //- - - - - - - - -//
 <p>Page that has a label.</p>
 //= = = = = = = = = = = = = = = = = = = = = = = =//
+18
+//- - - - - - - - -//
+Image: ![[hello.png]].
+//- - - - - - - - -//
+<p>Image: <img src="hello.png">.</p>
+//= = = = = = = = = = = = = = = = = = = = = = = =//
+19
+//- - - - - - - - -//
+Image: ![[hello.png|alt text]].
+//- - - - - - - - -//
+<p>Image: <img src="hello.png" alt="alt text"></p>
+//= = = = = = = = = = = = = = = = = = = = = = = =//
```

The text child gets added here: https://github.com/abhinav/goldmark-wikilink/blob/302a169fd266ec3cdab5aba4b623f13d50c4448a/parser.go#L94

I can think of a couple hacky ways to fix this:
- in parser, don't append the text child if embed is true
- in renderer, skip the children for the node if it's an image (and no alt text support)

But I think a more reliable fix for this is probably to
capture the text into a `Label []byte` field instead of/in addition to appending the child
and then letting the Renderer decide what to do with the text.
So we can do one of the following for a more reliable fix:

- Add a Label field to the Node type and still append the child.
  That causes some redundant information, but it's not too bad--they'll both reference the same byte slice so there won't be any copying.
  The Renderer will have to skip children for image nodes.
- Introduce a new EmbedNode type that has a Label field.
  Parser won't append a child to it.

**Comment by benclmnt** [comment]
ah yes, missed out on that interaction. I think both of your proposed reliable fix is fair, but I'm actually curious about the reason behind adding the text as a child instead of a simple field, say `Label []byte` as you mentioned.

**Comment by abhinav** [comment]
> I'm actually curious about the reason behind the parser adding the text as a child instead of a simple field, say `Label []byte` as you mentioned

The original reasons for this were two fold.
First, this matches what goldmark's ast.Link does.
More importantly, having the label inside child nodes leaves the possibility of expanding the library to support special inline nodes for labels.
For example, the children could be `text("foo "), emph("bar"), text(".")` for "foo **bar**" as the label.
This would not be possible with `Label []byte`.
Something like this isn't a necessity for embeds because the embed label is just extra optional information.

**Comment by abhinav** [comment]
@benclmnt I finally got a chance to get back to this.
Turns out the messy approach I suggested earlier wasn't necessary.
We can just extract the alt text from the child of the Node and render it as alt text, skipping the children.
I've pushed an update with this change to your branch.

**Pull request merged**
